version: '3.2'

services:    
  packetbeat:
    build:
      context: packetbeat/
      args:
        ELK_VERSION: $ELK_VERSION
    # Packetbeat needs some elevated privileges to capture network traffic.
    # We'll grant them with POSIX capabilities.
    cap_add: ['NET_RAW', 'NET_ADMIN']
    # Use "host mode" networking to allow Packetbeat to capture traffic from
    # the real network interface on the host, rather than being isolated to the
    # container's virtual interface.    
    network_mode: host

    command: -e -E 'output.elasticsearch.hosts=["18.215.157.192:5000"]'
    depends_on: ['elasticsearch']
    command: --strict.perms=false -e -E output.elasticsearch.hosts="http://18.215.157.192:5000" # -e flag to log to stderr and disable

    volumes:
      - type: bind
        source: ./packetbeat/config/packetbeat.yml
        target: /usr/share/packetbeat/config/packetbeat.yml
        read_only: true
