---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true

# SSL
server.ssl.enabled: true
elasticsearch.ssl.certificateAuthorities: /usr/share/kibana/config/certs/ca/ca.crt
server.ssl.key: /usr/share/kibana/config/certs/kibana/kibana.key
server.ssl.certificate: /usr/share/kibana/config/certs/kibana/kibana.crt

## X-Pack security credentials
#
elasticsearch.username: elastic
elasticsearch.password: changeme
