version: '3.2'

services:
  cowrie:
    restart: always
    build:
      context: .
      dockerfile: cowrie/Dockerfile
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - cowrie-etc:/cowrie/cowrie-git/etc
      - cowrie-var:/cowrie/cowrie-git/var
  
  filebeat:
    build:
      context: filebeat/
      args:
        ELK_VERSION: $ELK_VERSION   
    entrypoint: "filebeat -e -strict.perms=false" # disable strict permission checks
    user: root
    network_mode: host
    volumes:
      - type: bind
        source: ./filebeat/config/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true
    depends_on:
      - cowrie

volumes:
  cowrie-etc:
  cowrie-var:
