version: '3.2'

services:
  cowrie:
    restart: always
    build:
      context: .
      dockerfile: cowrie/Dockerfile
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - cowrie-etc:/cowrie/cowrie-git/etc
      - cowrie-var:/cowrie/cowrie-git/var

  filebeat:
    #image: docker.elastic.co/beats/filebeat:${TAG}
    container_name: filebeat
    entrypoint: "filebeat -e -strict.perms=false"
    #command: --strict.perms=false -e  
    # -e flag to log to stderr and disable syslog/file output
    # If the host system has logs at "/var/log", mount them at "/mnt/log"
    # inside the container, where Filebeat can find them.
    # volumes: ['/var/log:/mnt/log:ro']
    volumes:
      - type: bind
        source: ./filebeat/config/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true

networks:
  elk:
    driver: bridge

volumes:
  cowrie-etc:
  cowrie-var:
  filebeat:
  metricbeat:
