version: '3'

services:
  cowrie:
    restart: always
    build:
      context: .
      dockerfile: cowrie/Dockerfile
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - cowrie-etc:/cowrie/cowrie-git/etc
      - cowrie-var:/cowrie/cowrie-git/var

  dionaea:
    build:
      context: .
      dockerfile: dionaea/Dockerfile
    container_name: dionaea
    stdin_open: true
    tty: true
    restart: always
    network_mode: "host"
    ports:
      - "20:20"
      - "21:21"
      - "42:42"
      - "69:69/udp"
      - "81:81"
      - "135:135"
      - "443:443"
      - "445:445"
      - "1433:1433"
      - "1723:1723"
      - "1883:1883"
      - "3306:3306"
      - "5060:5060"
      - "5060:5060/udp"
      - "5061:5061"
      - "27017:27017"
    image: "dtagdevsec/dionaea:1903"
    read_only: true
    volumes:
      #- /data/dionaea/roots/ftp:/opt/dionaea/var/dionaea/roots/ftp
      #- /data/dionaea/roots/tftp:/opt/dionaea/var/dionaea/roots/tftp
      #- /data/dionaea/roots/www:/opt/dionaea/var/dionaea/roots/www
      #- /data/dionaea/roots/upnp:/opt/dionaea/var/dionaea/roots/upnp
      #- /data/dionaea:/opt/dionaea/var/dionaea
      #- /data/dionaea/binaries:/opt/dionaea/var/dionaea/binaries
      #- /data/dionaea/log:/opt/dionaea/var/log
      #- /data/dionaea/rtp:/opt/dionaea/var/dionaea/rtp

      - dionaea:/dionaea-git/ftp
      - dionaea:/dionaea-git/tftp
      - dionaea:/dionaea-git/www
      - dionaea:/dionaea-git/upnp
      - dionaea:/dionaea-git/var


  filebeat:
    #image: docker.elastic.co/beats/filebeat:${TAG}
    build:
      context: .
      dockerfile: filebeat/Dockerfile
      args:
        FILEBEAT_ARG: $FILEBEAT_ARG
    container_name: filebeat
    # command: --strict.perms=false -e  # -e flag to log to stderr and disable syslog/file output
    # If the host system has logs at "/var/log", mount them at "/mnt/log"
    # inside the container, where Filebeat can find them.
    # volumes: ['/var/log:/mnt/log:ro']
    #configs:
      #- source: ./filebeat/config
      #  target: /usr/share/filebeat/filebeat.yml
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      #- filebeat:/usr/share/filebeat/filebeat.yml:ro
      #- /var/run/docker.sock:/var/run/docker.sock
      # This is needed for filebeat to load container log path as specified in filebeat.yml
      #- /var/lib/docker/containers/:/var/lib/docker/containers/:ro

      # # This is needed for filebeat to load jenkins build log path as specified in filebeat.yml
      # - /var/lib/docker/volumes/jenkins_home/_data/jobs/:/var/lib/docker/volumes/jenkins_home/_data/jobs/:ro

      # This is needed for filebeat to load logs for system and auth modules
      #- /var/log/:/var/log/:ro
      - filebeat:/var/log/:ro
      # This is needed for filebeat to load logs for auditd module
      # - /var/log/audit/:/var/log/audit/:ro
    #volumes:
      #- './scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro'
    #networks: ['stack']
    #depends_on: ['elasticsearch', 'kibana']

networks:
  elk:
    driver: bridge

volumes:
  cowrie-etc:
  cowrie-var:
  filebeat:
  dionaea:
