version: '3'

services:
  cowrie:
    restart: always
    build:
      context: .
      dockerfile: cowrie/Dockerfile
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - cowrie-etc:/cowrie/cowrie-git/etc
      - cowrie-var:/cowrie/cowrie-git/var

networks:
  elk:
    driver: bridge

volumes:
  cowrie-etc:
  cowrie-var:
