  
ARG FILEBEAT_ARG

# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/beats/filebeat:${FILEBEAT_ARG}
#FROM docker.elastic.co/beats/filebeat:7.5.1

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu