  
ARG FILEBEAT_ARG

# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/beats/filebeat:${FILEBEAT_ARG}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu