filebeat.inputs:
- type: log
  paths:
    - /var/lib/docker/volumes/sb-honey_cowrie-var/_data/log/cowrie/cowrie.json*
  json.keys_under_root: true
  json.add_error_key: true
  fields:
    document_type: cowrie


output.logstash:
  enabled: true
  hosts: ["54.226.224.49:5000"]
  #protocol: "http"  
    
  # Authentication credentials - either API key or username/password.
  #api_key: "id:api_key"
  username: "elastic"
  password: "changeme"
