filebeat.inputs:
- type: log
  paths:
    - /var/lib/docker/volumes/sb-honey_cowrie-var/_data/log/cowrie/cowrie.json*
  fields:
    document_type: cowrie
  fields_under_root: true

output:
  logstash:
    hosts: ["34.235.112.115:5044"]
    bulk_max_size: 1024