# https://github.com/elastic/elasticsearch-docker
#FROM docker.elastic.co/beats/filebeat:${FILEBEAT_ARG}
FROM docker.elastic.co/beats/metricbeat:${ELASTIC_VERSION:-7.1.1}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu